// Code generated by "stringer -type=Op -trimprefix=Op"; DO NOT EDIT.

package diffmatchpatch

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpDelete - -1]
	_ = x[OpInsert-1]
	_ = x[OpEqual-0]
}

const _Op_name = "DeleteEqualInsert"

var _Op_index = [...]uint8{0, 6, 11, 17}

func (i Op) String() string {
	i -= -1
	if i < 0 || i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
